backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use common\components\keyStorage\FormModel;
use Yii;

/**
 * Site controller
 */
class SiteController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    public function beforeAction($action)
    {
        $this->layout = Yii::$app->user->isGuest || !Yii::$app->user->can('loginToBackend') ? 'base' : 'common';
        return parent::beforeAction($action);
    }

    public function actionSettings()
    {
        $model = new FormModel([
            'keys' => [
                'frontend.maintenance' => [
                    'label' => Yii::t('backend', 'Frontend maintenance mode'),
                    'type' => FormModel::TYPE_DROPDOWN,
                    'items' => [
                        'disabled' => Yii::t('backend', 'Disabled'),
                        'enabled' => Yii::t('backend', 'Enabled')
                    ]
                ],
                'backend.theme-skin' => [
                    'label' => Yii::t('backend', 'Backend theme'),
                    'type' => FormModel::TYPE_DROPDOWN,
                    'items' => [
                        'skin-black' => 'skin-black',
                        'skin-blue' => 'skin-blue',
                        'skin-green' => 'skin-green',
                        'skin-purple' => 'skin-purple',
                        'skin-red' => 'skin-red',
                        'skin-yellow' => 'skin-yellow'
                    ]
                ],
                'backend.layout-fixed' => [
                    'label' => Yii::t('backend', 'Fixed backend layout'),
                    'type' => FormModel::TYPE_CHECKBOX
                ],
                'backend.layout-boxed' => [
                    'label' => Yii::t('backend', 'Boxed backend layout'),
                    'type' => FormModel::TYPE_CHECKBOX
                ],
                'backend.layout-collapsed-sidebar' => [
                    'label' => Yii::t('backend', 'Backend sidebar collapsed'),
                    'type' => FormModel::TYPE_CHECKBOX
                ]
            ]
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('alert', [
                'body' => Yii::t('backend', 'Settings was successfully saved'),
                'options' => ['class' => 'alert alert-success']
            ]);
            return $this->refresh();
        }

        return $this->render('settings', ['model' => $model]);
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\AboutCategory;
use common\models\AboutOurPurposeAndMission;
use common\models\AboutPhoto;
use common\models\AboutProduct;
use common\models\AboutWhatDoWeOffer;
use common\models\AboutWhoAreWe;
use common\models\Articles;
use common\models\ContactAdmin;
use common\models\ContactRegion;
use common\models\DealerCategory;
use common\models\Email;
use common\models\Map;
use common\models\News;
use common\models\Order;
use common\models\Product;
use common\models\Region;
use common\models\Requisites;
use frontend\models\ContactForm;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction'
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null
            ],
            'set-locale' => [
                'class' => 'common\actions\SetLocaleAction',
                'locales' => array_keys(Yii::$app->params['availableLocales'])
            ]
        ];
    }

    public function actionIndex()
    {
        $products = Product::find()->where(['index' => true])->all();
        return $this->render('index', [
            'products' => $products,
        ]);
    }

    public function actionMaps()
    {
        $map = Map::find()->where(['id' => 1])->one();
        return $this->render('maps', [
            'map' => $map,
        ]);
    }

    public function actionSearch($search)
    {
        $products = Product::find()->andFilterWhere(['like', 'name', $search])->all();
        return $this->render('search', [
            'products' => $products,
        ]);
    }

    public function actionWhereBuy()
    {
        $regions = Region::find()->all();
        return $this->render('where-buy', [
            'regions' => $regions
        ]);
    }

    public function actionNews()
    {
        $lastNews = News::find()->orderBy(['id' => SORT_DESC])->one();

        $query = News::find()->orderBy(['id' => SORT_DESC])->andWhere(['<>', 'id', $lastNews->id]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 6]);
        $news = $query->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('news', [
            'news'  => $news,
            'lastNews' => $lastNews,
            'pages' => $pages,
        ]);
    }

    public function actionArticles()
    {
        $lastArticle = Articles::find()->orderBy(['id' => SORT_DESC])->one();

        $query = Articles::find()->orderBy(['id' => SORT_DESC])->andWhere(['<>', 'id', $lastArticle->id]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 6]);
        $article = $query->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('articles', [
            'article'  => $article,
            'lastArticle' => $lastArticle,
            'pages' => $pages,
        ]);
    }

    public function actionAbouts()
    {
        $aboutCategories = AboutCategory::find()->all();
        $block1 = AboutWhoAreWe::find()->where(['id' => 1])->one();
        $block2 = AboutWhatDoWeOffer::find()->where(['id' => 1])->one();
        $block3 = AboutProduct::find()->where(['id' => 1])->one();
        $block4 = AboutOurPurposeAndMission::find()->where(['id' => 1])->one();
        $photos = AboutPhoto::find()->all();

        return $this->render('abouts', [
            'aboutCategories'  => $aboutCategories,
            'block1'  => $block1,
            'block2'  => $block2,
            'block3'  => $block3,
            'block4'  => $block4,
            'photos'  => $photos,
        ]);
    }

    public function actionDealers()
    {
        $dealerCategories = DealerCategory::find()->all();
        return $this->render('dealers', [
            'dealerCategories' => $dealerCategories
        ]);
    }

    public function actionNewsPage($slug)
    {
        $news = News::find()->where(['slug' => $slug])->one();
        $newsAll = News::find()->orderBy(['id' => SORT_DESC])->limit(4)->all();
        return $this->render('news-page', [
            'news'    => $news,
            'newsAll' => $newsAll,
        ]);
    }

    public function actionArticlesPage($slug)
    {
        $articles = Articles::find()->where(['slug' => $slug])->one();
        $articlesAll = Articles::find()->orderBy(['id' => SORT_DESC])->limit(4)->all();
        return $this->render('articles-page', [
            'articles'    => $articles,
            'articlesAll' => $articlesAll,
        ]);
    }

    public function actionContacts()
    {
        $contactAdminModel  = ContactAdmin::find()->all();
        $contactRegionModel = ContactRegion::find()->all();
        $requisites = Requisites::find()->where(['id' => 1])->one();
        return $this->render('contacts', [
            'contactAdminModel'  => $contactAdminModel,
            'contactRegionModel' => $contactRegionModel,
            'requisites' => $requisites,
        ]);
    }

    public function actionServices()
    {
        return $this->render('services', []);
    }

    public function actionOrderAjax()
    {
        $firstname = Yii::$app->request->post('firstname');
        $lastname  = Yii::$app->request->post('lastname');
        $phone     = Yii::$app->request->post('phone');
        $country   = Yii::$app->request->post('country');
        $firm      = Yii::$app->request->post('firm');
        $position  = Yii::$app->request->post('position');
        $email     = Yii::$app->request->post('email');
        $product_id= Yii::$app->request->post('product_id');

        $order = new Order();
        $order->firstname = $firstname;
        $order->lastname = $lastname;
        $order->phone = $phone;
        $order->country = $country;
        $order->firm = $firm;
        $order->position = $position;
        $order->email = $email;
        $order->product_id = $product_id;
        $order->save();

        $product = Product::find()->where(['id' => $product_id])->one();

        $emailModel = Email::find()->where(['id' => 1])->one();
        $subject = 'Новый заказ';
        $msg = '<b>'.date('d-m-Y H:i:s').'</b>- поступил новый заказ<br/>'.
            'Имя: '.$firstname.' '.$lastname.'<br/>'.
            'Телефон: '.$phone.'<br/>'.
            'Страна: '.$country.'<br/>'.
            'Фирма: '.$firm.'<br/>'.
            'Должность: '.$position.'<br/>'.
            'Email:'.$email.'<br/>';
            'Товар:'.$product->name.'<br/>';
        mail($emailModel->email, $subject, $msg);
    }
}

frontend/views/site/abouts.php
<?php
require_once(Yii::getAlias('@frontend').'/views/layouts/section/seo.php');
?>
<header class="header__page">
    <div class="logo"><a href="/"><img src="/img/logo.svg"></a></div>
    <div class="breadcrumbs__wrapper">
        <div class="container">
            <h1><?= !empty($seo->h1) ? $seo->h1 : ''?></h1>
            <div class="breadcrumbs">
                <a class="back" href="#">&lt; Вернуться назад </a>
                <a class="breadcrumbs__item" href="/">Главная</a>
                <span class="breadcrumbs__item__span">></span>
                <?= \yii\helpers\Html::a('О нас', ['site/news'], ['class' => 'breadcrumbs__item'])?>
            </div>
        </div>
    </div>
    <svg class="icon hamburger">
        <use xlink:href="img/sprite.svg#icon-menu"></use>
    </svg>
        <?php
        require_once(Yii::getAlias('@frontend').'/views/layouts/section/search.php');
        ?>
</header>
<?php
require_once(Yii::getAlias('@frontend').'/views/layouts/section/nav.php');
?>
<!--main-->
<main class="main">
    <div class="content__wrapper about__company__page">
        <div class="content__min__width">
            <div class="tabs__wrapper">
                <h2 class="tabs__title">Разделы</h2>
                <?php foreach ($aboutCategories as $key=>$aboutCategory) { ?>
                    <div class="tabs__item <?= !$key ? 'active' : ''?>">
                        <a href="#about_<?= $aboutCategory->id?>"><?= $aboutCategory->name?></a>
                    </div>
                <? } ?>
            </div>
        </div>
        <div class="content__max__width">
            <svg class="icon icon__fixed">
                <use xlink:href="img/sprite.svg#icon-menu-fixed"></use>
            </svg>
            <h1 class="title__from__mobile"></h1>
            <section class="section__item" id="about_1">
                <div class="wrapper__about_company">
					<div class="section__title">
						<h2 class="russian"><?= $block1->title?></h2>
					</div>
                    <div class="content__about__us__flex section__wrapper reverse__block">
                        <div class="content__about__us__flex__img">
                            <img src="<?= $block1->getImgPath()?>">
                        </div>
                        <div class="content__about__us__flex__text">
                            <p>
                                <?= $block1->introtext?>
                            </p>
                        </div>
                    </div>
                    <div class="content__about__us__normal">
                        <p><?= $block1->text?></p>
                    </div>
                </div>
            </section>
            <section class="section__item" id="about_2">
                <div class="wrapper__about_company offers">
					<div class="section__title">
						<h2 class="russian"><?= $block2->title?></h2>
					</div>
                    <div class="content__about__us__flex section__wrapper">
                        <div class="content__about__us__flex__text">
                            <p><?= $block2->introtext?></p>
                        </div>
                        <div class="content__about__us__flex__img">
                            <div class="company__list">
                                <img src="<?= $block2->getImgPath()?>">
                            </div>
                        </div>
                    </div>
                    <div class="content__about__us__normal">
                        <p><?= $block2->text?></p>
                    </div>
                </div>
            </section>
            <section class="section__item" id="about_3">
                <div class="product__list">
                    <div class="product__list__item"><img src="<?= $block3->getImgPath()?>"></div>
                </div>
            </section>
            <section class="section__item" id="about_4">
                <div class="mission__wrapper">
                    <div class="mission__top">
                        <div class="section__title">
                            <h2 class="russian"><?= $block4->title?></h2>
                        </div>
                        <p><?= $block4->introtext?></p>
                    </div>
                    <div class="mission__bottom">
                        <p><?= $block4->text?></p>
                    </div>
                </div>
            </section>
            <section class="section__item" id="about_5">
                <div class="photo__about__us">
                    <?php foreach ($photos as $photo) {?>
                    <div class="photo__item"><img src="<?= $photo->getImgPath()?>"></div>
                    <? } ?>
                </div>
            </section>
            <?php
            require_once(Yii::getAlias('@frontend').'/views/layouts/section/footer.php');
            ?>
        </div>
    </div>
</main>

frontend/views/site/articles-page.php
<?php
$title = !empty($articles->seo_title)
    ? $articles->seo_title
    : '';

$keywords = !empty($articles->seo_keywords)
    ? $articles->seo_keywords
    : '';

$description = !empty($articles->seo_description)
    ? $articles->seo_description
    : '';

$this->title = $title;
$this->registerMetaTag([
    'name'    => 'keywords',
    'content' => $keywords
]);
$this->registerMetaTag([
    'name'    => 'description',
    'content' => $description
]);
// OG
$this->registerMetaTag([
    'property' => 'og:title',
    'content'  => $title
]);
$this->registerMetaTag([
    'property' => 'og:keywords',
    'content'  => $keywords
]);
$this->registerMetaTag([
    'property' => 'og:description',
    'content'  => $description
]);
$this->registerMetaTag([
    'property' => 'og:image',
    'content'  => '/img/logo_sm.png'
]);
$this->registerMetaTag([
    'property' => 'og:type',
    'content'  => 'website'
]);
$this->registerMetaTag([
    'property' => 'og:url',
    'content'  => 'http://belineco.com/'
]);
//DC
$this->registerMetaTag([
    'name'    => 'DC.creator',
    'content' => 'ООО АйТи Технолоджис Групп'
]);
$this->registerMetaTag([
    'name'    => 'DC.contributor',
    'content' => 'ESTEN / esten.co'
]);
$this->registerMetaTag([
    'name'     => 'DC:title',
    'content'  => $title
]);
$this->registerMetaTag([
    'name'    => 'DC.subject',
    'content' => $keywords
]);
$this->registerMetaTag([
    'name'    => 'DC.description',
    'content' => $description
]);
$this->registerMetaTag([
    'name'    => 'DC.language',
    'content' => 'ru-RU'
]);
$this->registerMetaTag([
    'name'    => 'DC.coverage',
    'content' => 'World'
]);
?>
<header class="header__page">
    <div class="logo"><a href="/"><img src="/img/logo.svg"></a></div>
    <div class="breadcrumbs__wrapper">
        <div class="container">
            <h1><?= $articles->title?></h1>
            <div class="breadcrumbs">
                <a class="back" href="#">&lt; Вернуться назад </a>
                <a class="breadcrumbs__item" href="/">Главная</a>
                <span class="breadcrumbs__item__span">></span>
                <?= \yii\helpers\Html::a('Статьи', ['site/articles'], ['class' => 'breadcrumbs__item'])?>
                <span class="breadcrumbs__item__span">></span>
                <?= \yii\helpers\Html::a($articles->title, ['site/articles-page', 'slug' => $articles->slug], ['class' => 'breadcrumbs__item'])?>
            </div>
        </div>
    </div>
    <svg class="icon hamburger">
        <use xlink:href="/img/sprite.svg#icon-menu"></use>
    </svg>
    <?php
    require_once(Yii::getAlias('@frontend').'/views/layouts/section/search.php');
    ?>
</header>
<?php
require_once(Yii::getAlias('@frontend').'/views/layouts/section/nav.php');
?>
<main class="main">
    <div class="news__wrapper">
        <div class="news__item__page">
            <h1 class="title__from__mobile">
                <?= $articles->title?>
            </h1>
            <div class="news__description">
                <?= $articles->description?>
            </div>
            <h1 class="title__more__news__list">Статьи</h1>
            <div class="more__news__list">
                <?php foreach ($articlesAll as $articles) {
                    echo \yii\helpers\Html::a('<div class="news__img">
                        <img src="'.$articles->getImgPath().'">
                    </div>
                    <h2>'.$articles->title.'</h2>
                    <span>'.$articles->introtext.'</span>', ['site/articles-page', 'slug' => $articles->slug], ['class' => 'little__news__item']);
                } ?>
            </div>
            <div class="button__news">
                <?= \yii\helpers\Html::a('Перейти к статьям', ['site/articles'], ['class' => 'more__news__button'])?>
            </div>
            <?php
            require_once(Yii::getAlias('@frontend').'/views/layouts/section/footer.php');
            ?>
        </div>
    </div>
</main>

frontend/views/site/articles.php
<?php
require_once(Yii::getAlias('@frontend').'/views/layouts/section/seo.php');
?>
<!--header-->
<header class="header__page">
    <div class="logo"><a href="/"><img src="/img/logo.svg"></a></div>
    <div class="breadcrumbs__wrapper">
        <div class="container">
            <h1><?= !empty($seo->h1) ? $seo->h1 : ''?></h1>
            <div class="breadcrumbs">
                <a class="back" href="#">&lt; Вернуться назад </a>
                <a class="breadcrumbs__item" href="/">Главная</a>
                <span class="breadcrumbs__item__span">></span>
                <?= \yii\helpers\Html::a('Информация', ['site/articles'], ['class' => 'breadcrumbs__item'])?>
            </div>
        </div>
    </div>
    <svg class="icon hamburger">
        <use xlink:href="img/sprite.svg#icon-menu"></use>
    </svg>
    <?php
    require_once(Yii::getAlias('@frontend').'/views/layouts/section/search.php');
    ?>
</header>
<?php
require_once(Yii::getAlias('@frontend').'/views/layouts/section/nav.php');
?>
<main class="main">
    <h1 class="title__from__mobile">Информация</h1>
    <div class="news__wrapper">
        <div class="news__content">
            <?= \yii\helpers\Html::a('<div class="news__img"><img src="'.$lastArticle->getImgPath().'"></div>
                <h2>'.$lastArticle->title.'</h2>
                <span>'.$lastArticle->introtext.'</span>', ['site/articles-page', 'slug' => $lastArticle->slug] , ['class' => 'big__news'])?>
            <div class="little__news__list">
                <?php foreach ($article as $key=>$item) {?>
                    <?= \yii\helpers\Html::a('<div class="news__img"><img src="'.$item->getImgPath().'"></div>
                    <h2>'.$item->title.'</h2>
                    <span>'.$item->introtext.'</span>', ['site/articles-page', 'slug' => $item->slug], ['class' => 'little__news__item'])?>
                <? } ?>
            </div>
        </div>
        <?= \yii\widgets\LinkPager::widget([
            'pagination' => $pages,
        ]); ?>
        <!--<div class="pagination"><a class="pagination__item" href="#">Первая</a>
            <ul>
                <li><a href="#">
                        <svg class="icon">
                            <use xlink:href="img/sprite.svg#icon-pagination-prev"></use>
                        </svg></a></li>
                <li class="active"><a href="#">10</a></li>
                <li><a href="#">11</a></li>
                <li><a href="#">..</a></li>
                <li><a href="#">25</a></li>
                <li><a href="#">26</a></li>
                <li><a href="#">
                        <svg class="icon">
                            <use xlink:href="img/sprite.svg#icon-pagination-next"></use>
                        </svg></a></li>
            </ul><a class="pagination__item" href="#">Последняя</a>
        </div>-->
        <?php
        require_once(Yii::getAlias('@frontend').'/views/layouts/section/footer-box.php');
        ?>
    </div>
</main>

frontend/views/site/contacts.php
<?php
require_once(Yii::getAlias('@frontend').'/views/layouts/section/seo.php');
?>
<header class="header__page">
    <div class="logo"><a href="/"><img src="/img/logo.svg"></a></div>
    <div class="breadcrumbs__wrapper">
        <div class="container">
            <h1><?= !empty($seo->h1) ? $seo->h1 : ''?></h1>
            <div class="breadcrumbs">
                <a class="back" href="#">&lt; Вернуться назад </a>
                <a class="breadcrumbs__item" href="/">Главная</a>
                <span class="breadcrumbs__item__span">></span>
                <?= \yii\helpers\Html::a('Контакты', ['site/contacts'], ['class' => 'breadcrumbs__item'])?>
            </div>
        </div>
    </div>
    <svg class="icon hamburger">
        <use xlink:href="img/sprite.svg#icon-menu"></use>
    </svg>
    <?php
    require_once(Yii::getAlias('@frontend').'/views/layouts/section/search.php');
    ?>
</header>
<?php
require_once(Yii::getAlias('@frontend').'/views/layouts/section/nav.php');
?>
<main class="main">
    <div class="contact__page">
        <h1 class="title__from__mobile">
            КОНТАКТЫ</h1>
        <h2 class="contact__title">
            <div class="container"><p>Администрация</p></div>
        </h2>
        <?php foreach ($contactAdminModel as $contactAdmin) {?>
        <div class="contact__background">
            <div class="container">
                <div class="contact__item">
                    <div class="position">
                        <p><?= $contactAdmin->position?></p>
                    </div>
                    <div class="contact__info">
                        <div class="name"><?= $contactAdmin->name?></div>
                        <?php if ($contactAdmin->phone_mob) {?>
                            <div class="title__contact__item">Мобильный</div>
                            <div class="info__contact__item"><?= $contactAdmin->phone_mob?></div>
                        <? } ?>
                        <?php if ($contactAdmin->phone_home) {?>
                            <div class="title__contact__item">Телефон</div>
                            <div class="info__contact__item"><?= $contactAdmin->phone_home?></div>
                        <? } ?>
                        <?php if ($contactAdmin->fax) {?>
                            <div class="title__contact__item">Факс</div>
                            <div class="info__contact__item"><?= $contactAdmin->fax?></div>
                        <? } ?>
                        <?php if ($contactAdmin->email) {?>
                            <div class="title__contact__item">Email</div>
                            <div class="info__contact__item">
                                <a href="mailto:<?= $contactAdmin->email?>">
                                <?= $contactAdmin->email?>
                                </a>
                            </div>
                        <? } ?>
                        <?php if ($contactAdmin->skype) {?>
                            <div class="title__contact__item">Skype</div>
                            <div class="info__contact__item"><?= $contactAdmin->skype?></div>
                        <? } ?>
                    </div>
                </div>
            </div>
        </div>
        <? } ?>

        <h2 class="contact__title">
            <div class="container">Региональные представители</div>
        </h2>
        <?php foreach ($contactRegionModel as $contactRegion) {?>
        <div class="contact__background">
            <div class="container">
                <div class="contact__item content__item__block__wrapper">
                    <div class="contact__item__block">
                        <div class="position">
                            <p>Страна / Область / Город</p>
                        </div>
                        <div class="contact__info">
                            <div class="name"><?= $contactRegion->contactRegionName->name?></div>
                            <div class="title__contact__item">региональный склад</div>
                            <div class="info__contact__item"><?= $contactRegion->contactRegionName->address?></div>
                        </div>
                    </div>
                    <div class="contact__item__block">
                        <div class="position">
                            <p><?= $contactRegion->position?></p>
                        </div>
                        <div class="contact__info">
                            <div class="name"><?= $contactRegion->name?></div>
                            <?php if ($contactRegion->phone_mob) {?>
                                <div class="title__contact__item">Мобильный</div>
                                <div class="info__contact__item"><?= $contactRegion->phone_mob?></div>
                            <? } ?>
                            <?php if ($contactRegion->phone_home) {?>
                                <div class="title__contact__item">Телефон</div>
                                <div class="info__contact__item"><?= $contactRegion->phone_home?></div>
                            <? } ?>
                            <?php if ($contactRegion->fax) {?>
                                <div class="title__contact__item">Факс</div>
                                <div class="info__contact__item"><?= $contactRegion->fax?></div>
                            <? } ?>
                            <?php if ($contactRegion->email) {?>
                                <div class="title__contact__item">Email</div>
                                <div class="info__contact__item">
                                    <a href="mailto:<?= $contactRegion->email?>">
                                        <?= $contactRegion->email?>
                                    </a>
                                </div>
                            <? } ?>
                            <?php if ($contactRegion->skype) {?>
                                <div class="title__contact__item">Skype</div>
                                <div class="info__contact__item"><?= $contactRegion->skype?></div>
                            <? } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <? } ?>
        <?php if (!empty($requisites->bank)) {?>
        <h2 class="contact__title">
            <div class="container">ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ</div>
        </h2>
        <div class="contact__background">
            <div class="container">
                <div class="contact__item">
                    <div class="position">
                        <p>Банковские реквизиты</p>
                    </div>
                    <div class="contact__info">
                        <?php if ($requisites->address_legal) {?>
                            <div class="title__contact__item">Юридический адрес</div>
                            <div class="info__contact__item"><?= $requisites->address_legal?></div>
                        <? } ?>
                        <?php if ($requisites->bic) {?>
                            <div class="title__contact__item">BIC</div>
                            <div class="info__contact__item"><?= $requisites->bic?></div>
                        <? } ?>
                        <?php if ($requisites->iban) {?>
                            <div class="title__contact__item">IBAN</div>
                            <div class="info__contact__item"><?= $requisites->iban?></div>
                        <? } ?>
                        <?php if ($requisites->bank) {?>
                            <div class="title__contact__item">Банк</div>
                            <div class="info__contact__item"><?= $requisites->bank?></div>
                        <? } ?>
                        <?php if ($requisites->address) {?>
                            <div class="title__contact__item">Адрес</div>
                            <div class="info__contact__item"><?= $requisites->address?></div>
                        <? } ?>
                    </div>
                </div>
            </div>
        </div>
        <? } ?>
        <?php
        require_once(Yii::getAlias('@frontend').'/views/layouts/section/footer-box.php');
        ?>
    </div>
</main>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?php echo Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?php echo nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
require_once(Yii::getAlias('@frontend').'/views/layouts/section/header.php');
require_once(Yii::getAlias('@frontend').'/views/layouts/section/nav.php');
require_once(Yii::getAlias('@frontend').'/views/layouts/section/seo.php');
?>
<!--main-->
<main class="main">
    <div class="slider-for">
        <?php foreach ($products as $product) { ?>
        <div class="slider__item">
            <div class="slider__wrapper">
                <div class="slider__content">
                    <p>Продукт</p>
                    <h2><?= $product->name?></h2><!--<span><?/*= $product->introtext*/?> </span>-->
                    <div class="link__more">
                        <?= \yii\helpers\Html::a('Подробнее', ['catalog/page', 'slug' => $product->slug])?>
                    </div>
                </div>
                <div class="slider__img" style="background: url(<?= $product->getImgPath() ;?>) no-repeat;   background-size: contain; background-position: center;">
                </div>
            </div>
        </div>
        <? } ?>
    </div>
    <div class="slider-nav">
        <?php $i = 1;?>
        <?php foreach ($products as $product) { ?>
        <div class="slider__item__nav">
            <div class="nav__slide">
                <div class="nav__tro">
                    <p class="number__slide"><?= $i?></p>
                    <p class="title__slide"><?= $product->name?></p>
                </div>
            </div>
        </div>
        <? $i++;} ?>
    </div>
    <div class="slider-progress">
        <div class="progress"></div>
    </div>
</main>
<!--footer-->